#server
server:
  port: 8761

#eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    fetch-registry: false
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000